/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/female_head/scene.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 589.868, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Head001__0.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_1.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_2.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_3.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_4.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_5.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_6.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_7.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_8.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_9.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_10.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_11.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_12.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_13.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_14.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_15.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_16.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_17.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_18.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_19.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_20.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_21.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_22.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_23.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_24.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Head001__0_25.geometry} material={materials['Scene_-_Root']} />
        </group>
        <mesh geometry={nodes.Sphere001__0.geometry} material={materials['Scene_-_Root']} position={[90.528, 517.545, 180.374]} scale={41.795} />
        <mesh geometry={nodes.NurbsPath002__0.geometry} material={materials['Scene_-_Root']} rotation={[2.036, -0.205, 0.71]} scale={4.923} />
        <mesh geometry={nodes.Mesh002__0.geometry} material={materials['Scene_-_Root']} position={[0, 589.868, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.NurbsPath001__0.geometry} material={materials['Scene_-_Root']} rotation={[2.036, 0.205, -0.71]} scale={[-4.923, 4.923, 4.923]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.glb')
